name: Create Jira Issue
on:
  issues:
    types:
      - opened

jobs:
  create:
    runs-on: ubuntu-latest
    name: Create Jira Issue
    steps:
      - name: Create Jira Issue
        uses: weareinreach/action-create-jira-issue@main
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        with:
          project: IN
          issuetype: GitHub
          summary: ${{ github.event.issue.title }}
